//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBrain.Applications.MyRadioPlayer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MyRadioPlayerResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyRadioPlayerResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyBrain.Applications.MyRadioPlayer.Resources.MyRadioPlayerResource", typeof(MyRadioPlayerResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BBCRadio1_Logo {
            get {
                object obj = ResourceManager.GetObject("BBCRadio1_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Capital_95_8_FM_Logo {
            get {
                object obj = ResourceManager.GetObject("Capital_95_8_FM_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CapRadio_Log {
            get {
                object obj = ResourceManager.GetObject("CapRadio_Log", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ExpressFM_Logo {
            get {
                object obj = ResourceManager.GetObject("ExpressFM_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IFM_Logo {
            get {
                object obj = ResourceManager.GetObject("IFM_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kalima_Logo {
            get {
                object obj = ResourceManager.GetObject("kalima_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio Logo:.
        /// </summary>
        internal static string lblRadioLogo {
            get {
                return ResourceManager.GetString("lblRadioLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio Name:.
        /// </summary>
        internal static string lblRadioName {
            get {
                return ResourceManager.GetString("lblRadioName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio Url Streaming:.
        /// </summary>
        internal static string lblRadioUrlStreaming {
            get {
                return ResourceManager.GetString("lblRadioUrlStreaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio WebSite:.
        /// </summary>
        internal static string lblRadioWebSite {
            get {
                return ResourceManager.GetString("lblRadioWebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio Stations.
        /// </summary>
        internal static string lblTreeViewRoot {
            get {
                return ResourceManager.GetString("lblTreeViewRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MFM_Logo {
            get {
                object obj = ResourceManager.GetObject("MFM_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Monastir_Logo {
            get {
                object obj = ResourceManager.GetObject("Monastir_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MosaiqueFM_Logo {
            get {
                object obj = ResourceManager.GetObject("MosaiqueFM_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffering Started....
        /// </summary>
        internal static string msgBufferingStarted {
            get {
                return ResourceManager.GetString("msgBufferingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is playing..
        /// </summary>
        internal static string msgIsPlaying {
            get {
                return ResourceManager.GetString("msgIsPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Ended!!!.
        /// </summary>
        internal static string msgMediaEnded {
            get {
                return ResourceManager.GetString("msgMediaEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Failed!!!.
        /// </summary>
        internal static string msgMediaFailed {
            get {
                return ResourceManager.GetString("msgMediaFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Paused.
        /// </summary>
        internal static string msgMediaPaused {
            get {
                return ResourceManager.GetString("msgMediaPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Stoped.
        /// </summary>
        internal static string msgMediaStoped {
            get {
                return ResourceManager.GetString("msgMediaStoped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Nationale_Logo {
            get {
                object obj = ResourceManager.GetObject("Nationale_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Nrj_Logo {
            get {
                object obj = ResourceManager.GetObject("Nrj_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RTCI_Logo {
            get {
                object obj = ResourceManager.GetObject("RTCI_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ShemsFM_Logo {
            get {
                object obj = ResourceManager.GetObject("ShemsFM_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string txtBlkSatus {
            get {
                return ResourceManager.GetString("txtBlkSatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stat:.
        /// </summary>
        internal static string txtBlkStat {
            get {
                return ResourceManager.GetString("txtBlkStat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        internal static string txtBlkVolume {
            get {
                return ResourceManager.GetString("txtBlkVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Zitouna_Logo {
            get {
                object obj = ResourceManager.GetObject("Zitouna_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
